"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const users_1 = require("../controllers/users");
const router = (0, express_1.Router)();
router.get("/users", users_1.getUsers);
router.get("/users/count", users_1.getTotalUsers);
router.get("/users/:id", users_1.getUserById);
router.post("/users", users_1.createUser);
router.put("/users/:id", users_1.updateUserById);
router.delete("/users/:id", users_1.deleteUserById);
exports.default = router;
